services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    networks:
      - hvac-net

  nodered:
    image: nodered/node-red:latest
    container_name: hvac-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - mosquitto
    networks:
      - hvac-net

  backend:
    # build:
    #   context: ./backend
    image: snikehero/hvac-backend:1.0
    container_name: hvac-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      NODE_ENV: development
    depends_on:
      - mosquitto
    networks:
      - hvac-net

  frontend:
    # build:
    #   context: ./hvac-frontend
    image: snikehero/hvac-frontend:1.0
    container_name: hvac-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - hvac-net
    volumes:
      - .:/app
networks:
  hvac-net:
    driver: bridge
